name: PR Check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".gitignore"
      - "config-example.json"
      - "LICENSE"
      - "README.md"
      - ".github/dependabot.yml"

concurrency:
  group: pr-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-check:
    name: PR Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
          cache: true

      - name: Build check
        run: go build ./...

      - name: Test (optional)
        run: go test ./... || true